kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
 containers:
 - name: nginx
   image: nginx
   resources:
   # soft limit
     memory: "64Mi"
     cpu: "100m"
     #hard limit
   limits:
     memory: "128Mi"
     cpu: "150m"
