kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
   # soft limit
         memory: "64Mi"
         cpu: "100m"
      limits:
   # hard link
         memory: "128Mi"
         cpu: "150m"
