kind: Pod
apiVersion: v1
metadata:
 name: taint
 namespace: expense
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx 
    image: nginx:latest
  tolerations:
  - key: "hardware"
    operator: Equal
    value: "gpu"
    effect: NoExecute  